version: '3.9'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    command: >
      python aggregation_cli.py
      --inputs_path /data/inputs
      --outputs_path /data/outputs/census_places 
      --cross_table_path /data/inputs/crosswalk_files/blockgroup_place_crosswalk_all_vehicles.parquet
      --aggregation_col place_name
      